export const BANNED_PHRASES: string[] = [
  "hidden gem",
  "vibrant culture",
  "rich culture",
  "unforgettable experience",
  "once-in-a-lifetime",
  "breathtaking views",
  "stunning scenery",
  "warm hospitality",
  "nestled in the heart of",
  "off the beaten path",
  "must-see",
  "must-visit",
  "paradise",
  "heaven on earth",
  "a feast for the senses",
  "steeped in history",
  "where tradition meets modernity",
  "a journey of discovery",
  "immerse yourself in",
  "escape the hustle and bustle",
  "hidden treasures",
  "picture-perfect",
  "postcard-perfect",
  "something for everyone",
  "look no further",
  "you won't be disappointed",
  "vibrant",
  "seamless",
  "empower",
  "unlock",
  "elevate",
  "transform",
  "revolutionize",
  "supercharge",
];
